timeout 1
default Nerves
menu title boot nerves on Fairphone 3+

label Nerves
	kernel /Image
	fdt /sdm632-fairphone-fp3p.dtb
	initrd /initramfs.gz
	append earlycon console=ttyMSM0,115200 console=tty0 loglevel=8 fbcon=rotate:3 fbcon=font:TER16x32 rootfs=/dev/mmcblk0p62p2 bootpart=/dev/mmcblk0p62p1 rootfstype=squashfs ro rootwait panic=30
